### ISSUE TITLE
002 - Provide a link to the counter-proposal

### ISSUE THREAD

**Issue by wycats** [nodejs/node-eps#25]
In addition to characterizing the counter-proposal (in my opinion, incorrectly), it would be helpful if this document linked directly to the counterproposal (https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md).

I understand that the CTC has decided to go with `.mjs`, but for posterity it would be helpful if future readers of this decision could easily find the proposal it is criticizing.

**Comment by trevnorris** [comment]
Would you like this link in the document? If so, please open a PR. Because I highly doubt anyone else will take the time to do it. :)
