### ISSUE TITLE
002 ES modules in a `vm`

### ISSUE THREAD

**Issue by cpojer** [nodejs/node-eps#35]
I'm curious how the proposal for handling ES2015 modules in node will work with the `vm` module. Specifically I am interested in how to intercept imports during runtime.

Currently I can inject my own implementation of `require` into a context and then run JavaScript code inside of the context. This allows me to control how to resolve modules.

Are there hooks planned for manipulating/intercepting import/export in a vm?

**Comment by bmeck** [comment]
Eventually once we have everything ironed out we will spec something like `vm.ParseModule` and `vm.ModuleDeclarationInstanciation` and `vm.ModuleEvaluation`.

These correspond the the hooks node needed from the spec itself and should work across VMs.

Spec links: 
- [ParseModule](https://tc39.github.io/ecma262/#sec-parsemodule)
- [ModuleDeclarationInstanciation](https://tc39.github.io/ecma262/#sec-moduledeclarationinstantiation)
- [ModuleEvaluation](https://tc39.github.io/ecma262/#sec-moduleevaluation)

You will most likely need to implement the loader yourself inside of that. This approach lets us do things like have JSDom have a completely separate loader with the slightly differing async semantics from the Node core loader.

**Comment by cpojer** [comment]
Thanks for the response, this is great!
