### ISSUE TITLE
Archiving this repo

### ISSUE THREAD

**Issue by jasnell** [nodejs/node-eps#65]
The @nodejs/tsc has [decided](https://github.com/nodejs/TSC/issues/335) to archive this repo and move away from the node-eps process. See https://github.com/nodejs/TSC/issues/335 for details.

**Comment by trevnorris** [comment]
@jasnell so would the large number of comments for modules not have happened if it'd been placed in a PR? and where would a proposal like es modules have gone for implementation discussion?

**Comment by jasnell** [comment]
Presumably in a separate working fork like what we've done with node-chakracore and http2 ... both of which worked out rather well.

**Comment by Fishrock123** [comment]
https://github.com/nodejs/TSC/issues/335#issuecomment-330893808 (Me):
> ... I am not for this. I think it is useful and it should be used more.

**Comment by guybedford** [comment]
Would it make sense to revisit this decision given recent events?

**Comment by ljharb** [comment]
@guybedford what recent events?

**Comment by jasnell** [comment]
I don't believe so. There's nothing that could be done here that can't be done working on actual code in working repos.

**Comment by guybedford** [comment]
I'm referring to the discussions in the current fetch / websocket feature issues in the main repo.

Yeah it doesn't seem this repo would help that either.

Perhaps some process around curated long discussions would be useful though - for example if I knew I was posting a particularly controversial feature request / issue discussion / PR to be able to create and link to a special discussion page that would have curation and per-comment voting / threading. Is there anything close to this in place currently?

**Comment by Trott** [comment]
Superseded by https://github.com/nodejs/admin/issues/160. Closing.
